name: Docker Image CI

on:
  push:
    branches:
      - 'master'
    tags:
      - '*'
    paths-ignore:
      - '**.md'
  pull_request:

env:
  DOCKERHUB_SLUG: sigurdh/docker-fail2ban
  
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: |
          ${{ env.DOCKERHUB_SLUG }}
        tags: |
          type=match,pattern=(.*)-r,group=1
          type=ref,event=pr
          type=edge
        labels: |
          org.opencontainers.image.title=Fail2ban
          org.opencontainers.image.description=Intrusion prevention software framework that protects computer servers from brute-force attacks
            
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Login to DockerHub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build
      uses: docker/bake-action@v2
      with:
        files: |
          ./docker-bake.hcl
          ${{ steps.meta.outputs.bake-file }}
        targets: image-all
        push: ${{ github.event_name != 'pull_request' }}
